In [1]:
import numpy as np

In [50]:
# initial params
I = np.eye(3)
gamma = 0.9
P_pi = np.array([[0.1, 0, 0.9],
                 [0.9, 0.1, 0],
                 [0.9, 0, 0.1]])
r_pi = np.array([-0.9,-0.1,-0.1])

In [51]:
v = np.linalg.inv(I-gamma*P_pi) @ r_pi
v

array([-5.23255814, -4.76744186, -4.76744186])

In [52]:
# initial params
I = np.eye(3)
gamma = 0.9
# 2 actions reprensented by 2 matrices

P_a1 = np.array([[0.1, 0, 0.9],
                 [0.9, 0.1, 0],
                 [0.9, 0, 0.1]])

P_a2 = np.array([[0.1, 0.9, 0],
                 [0.9, 0.1, 0],
                 [0.9, 0, 0.1]])


P_pi = (P_a1 + P_a2)/2


r_a1 = np.array([-0.9,-0.1,-0.1])
r_a2 = np.array([-0.9,-0.1,-0.1])

r_pi = (r_a1 + r_a2)/2

In [53]:
v = np.linalg.inv(I-gamma*P_pi) @ r_pi
v

array([-5.23255814, -4.76744186, -4.76744186])

In [54]:
# by recursion 
v = np.zeros((3,))
for k in range(1000):
    v = r_pi + gamma*v

In [55]:
v

array([-9., -1., -1.])